
#Simple Linear Regression
data = read.csv("C:/Users/Ltbc7/Google Drive (mjbouvet@iu.edu)/Data Mining/Homework 6/Vocab.csv",stringsAsFactors=FALSE, sep=",")
print(data)

X1 = as.matrix(data[,4])
height = nrow(data)
X0 = matrix(1, height)
print(X0)

X = cbind(X0,X1)
print(X) #(a)
Y = as.matrix(data[,5])
plot(X1, Y)
a = solve(t(X) %*% X, t(X) %*% Y)  
cat("a and b are ,", a[2], a[1], "/n") #(b)



#as the function is increasing that means as the education level increases there is a trend toward a higher vocabulary level as well so yes it does
#appear that a higher education level results in a higher vocabulary level based on this data

#As the slope of the line generated will be a which is equal to .3318736 then it tells us that each year the score on the vocabulary test approximately
#increased by .3318736 so that would be the value of a extra year of education regarding increase of vocabulary


#Example 2 of Linear Regression
dat = read.csv("C:/Users/Ltbc7/Google Drive (mjbouvet@iu.edu)/Data Mining/Homework 6/ais.csv",stringsAsFactors=FALSE, sep=",")


X1 = as.matrix(dat[,3:12])
X0 = matrix(1, nrow(dat))
X = cbind(X0, X1)
print(X)
Y = as.matrix(dat[,2])
print(Y)
a = solve(t(X) %*% X, t(X) %*% Y) 
cat(a, '\n')       	      	

yhat = X %*% a	 # our predictions of y values
error = Y - yhat
sse = sum(error*error)  # sum of squared error.  We chose a by minimizing this.  
cat(sse, '\n') 

for (d in 1:10) {
  Xi = as.matrix(dat[,3:12]);
  #print(Xi)
  xf <- Xi[,-d]
  onecol = matrix(1, nrow(xf))
  xff = cbind(onecol, xf)
  #print(xf)
  Y = as.matrix(dat[,2])
  a = solve(t(xff) %*% xff, t(xff) %*% Y)
  yhat = xff %*% a
  error = Y - yhat
  sse = sum(error*error)
  cat("with the ", colnames(dat)[d+2], " variable  removed sse of ", sse, "\n");
  
}

#The variable in which the error increases the most is variable 4, namely the hc variable 
#which also leads to show hc is the most important variable in deciding rcc

#Exponential and Periodic Regression

data(nottem)
y = nottem
#print(y)
n = length(y)
x = 1:n;

plot(x,y, type = "b")

X0 = matrix(1, n)
X1 = as.matrix(x)
X = cbind(X0, X1)
Y = as.matrix(y)
#print(Y)
a = solve(t(X) %*% X, t(X) %*% y)
cat("a and b are ,", a[2], a[1], "\n")
abline(a[1], a[2], col = 2)


X = cbind(rep(1,n), cos(2*pi*x/12),sin(2*pi*x/12))
a = solve(t(X) %*% X, t(X) %*% y);
print(a)
yhat = X %*% a
lines(x, yhat, col = 4)

cat("a, b, and C are: ", a[3],a[2],a[1], "\n")
#a, b, and c are -6.940906, -9.240921, 49.03958


X = cbind(rep(1,n), x, cos(2*pi*x/12), sin(2*pi*x/12))
a = solve(t(X) %*% X, t(X) %*% y);
print(a)
yhat = X %*% a
lines(x, yhat, col = 3)
cat("a, b, c, and d are: ", a[4],a[3],a[1], a[2], "\n")
#a,b,c and d are -6.924513, -9.245314, 48.51032, and .004392239
#as a result this does show a growth in sales as the .004392239 value for d will cause a slight upward trend in the periodic function
#generated by a,b, and c, its very minimal so there is slow growth but yes there is growth in sales as the months progress

#Season Model Regression
data(AirPassengers)
y = AirPassengers
n = length(y)
x = 1:n
print(y)


#(a)
plot(x, log(y), type = "b")
#The model will be a seasonal model of yi * a cos(2pi*xi/12) + b sin(2pi*xi/12) + c + dxi as it has an increasing part and is seasonal

#(b)
X = cbind(rep(1,n), x, cos(2*pi*x/12), sin(2*pi*x/12))
a = solve(t(X)%*%X, t(X)%*% log(y))
print(a)
yhat = X %*% a
lines(x, yhat, col = 4)


#(c)
plot(x, y, type ="b")
X = cbind(rep(1,n), x, cos(2*pi*x/12), sin(2*pi*x/12))
a = solve(t(X)%*%X, t(X)%*% y)
print(a)
yhat = X %*% a
lines(x, yhat, col = 4)
